baseURL = "https://tkdc926.github.io/"
languageCode = "en-us"
title = "Binario"
theme = "Binario"
paginate = 10
googleAnalytics = ""
publishDir = "tkdc926.github.io"

[Params]
  description = "Responsive card-based & code-light Hugo theme"
  columns = 2
